/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel_System;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasitha
 */
public class Hotel_System extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_System
     */
    public Hotel_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName = new javax.swing.JLabel();
        CustomerRef = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        CustomerMobile = new javax.swing.JLabel();
        IdNo = new javax.swing.JLabel();
        Nationality = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtCustomerRef = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCustomerMobile = new javax.swing.JTextField();
        txtIdNo = new javax.swing.JTextField();
        jLocalNationality = new com.toedter.components.JLocaleChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CheckIn = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        RoomType = new javax.swing.JLabel();
        CheckOut = new javax.swing.JLabel();
        RoomExtNo = new javax.swing.JLabel();
        RoomNo = new javax.swing.JLabel();
        comboRoomExtNo = new javax.swing.JComboBox<>();
        jDateCheckOut = new com.toedter.calendar.JDateChooser();
        jDateCheckIn = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        YourBill = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        txtYourBill = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        TotalCost = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        comboGender = new javax.swing.JComboBox<>();
        comboRoomType = new javax.swing.JComboBox<>();
        comboRoomNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstName.setText("First Name :");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        CustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerRef.setText("Customer Ref:");
        getContentPane().add(CustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address : ");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.setText("Last Name :");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Email.setText("Email :");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        CustomerMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerMobile.setText("Customer Mobile :");
        getContentPane().add(CustomerMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        IdNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IdNo.setText("National Id Number :");
        getContentPane().add(IdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        Nationality.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nationality.setText("Nationality :");
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        txtFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 250, -1));

        txtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCustomerRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerRefActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 250, -1));

        txtLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 250, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 250, -1));

        txtCustomerMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCustomerMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerMobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomerMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, -1));

        txtIdNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 250, -1));

        jLocalNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLocalNationalityActionPerformed(evt);
            }
        });
        getContentPane().add(jLocalNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Ref :", "First Name :", "Last Name :", "Address :", "customer Mobile :", "Email :", "Nationality :", "National Id Nu :", "Gender :", "Check In Date :", "Check Out Date :", "Room Type :", "Room No :", "Room Ext. No :"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 1080, 410));

        CheckIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckIn.setText("Check In Date :");
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gender.setText("Gender :");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        RoomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoomType.setText("Room Type :");
        getContentPane().add(RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckOut.setText("Check Out Date :");
        getContentPane().add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        RoomExtNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoomExtNo.setText("Room Ext. No :");
        getContentPane().add(RoomExtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        RoomNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoomNo.setText("Room No  :");
        getContentPane().add(RoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 20));

        comboRoomExtNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboRoomExtNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Ext No", "101", "102", "03", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "017", "018", "019", "020" }));
        getContentPane().add(comboRoomExtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 250, -1));
        getContentPane().add(jDateCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 250, -1));
        getContentPane().add(jDateCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 250, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        YourBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        YourBill.setText("Your Bill :");

        Tax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tax.setText("Tax :");

        Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Total.setText("Total :");

        txtYourBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtYourBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYourBillActionPerformed(evt);
            }
        });

        txtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        Reset.setBackground(java.awt.Color.orange);
        Reset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Exit.setBackground(java.awt.Color.red);
        Exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Update.setBackground(java.awt.Color.green);
        Update.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        TotalCost.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TotalCost.setText("Total Cost");
        TotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCostActionPerformed(evt);
            }
        });

        Add.setBackground(java.awt.Color.blue);
        Add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YourBill)
                    .addComponent(Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtYourBill, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal))
                .addGap(330, 330, 330)
                .addComponent(TotalCost)
                .addGap(18, 18, 18)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtYourBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(92, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(YourBill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 1560, 200));

        comboGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 250, -1));

        comboRoomType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "Single", "Double", "Villa", "Apartment" }));
        getContentPane().add(comboRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 250, -1));

        comboRoomNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room No", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014", "015", "016", "017", "018", "019", "020" }));
        getContentPane().add(comboRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 250, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtCustomerRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerRefActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCustomerMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerMobileActionPerformed

    private void txtIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNoActionPerformed

    private void jLocalNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocalNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLocalNationalityActionPerformed

    private void txtYourBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYourBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourBillActionPerformed

    private void txtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()== -1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete ",
                        "Hotel Management System", JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showMessageDialog(null, "Select Row to delete ",
                        "Hoptel System ",JOptionPane.OK_OPTION);
            }
        }
        else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteActionPerformed
    private JFrame frame;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if You want to exit", "Return The System", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
             if (jTable1.getRowCount() == 0){
                 JOptionPane.showMessageDialog(null, "Update Confirm" , "Return The System",
                         JOptionPane.OK_OPTION);
             }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void TotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCostActionPerformed
        
        int SingleRoom = 35;
        int DoubleRoom = 55;
        int Villa = 100;
        int Apartment = 80;
        
        SimpleDateFormat format = new SimpleDateFormat("yyyy-mm-dd");
        Date Check_In_Date = null;
        Date Check_Out_Date = null;
        
        try{
            Check_In_Date = format.parse(format.format(jDateCheckIn.getDate()));
            Check_Out_Date = format.parse(format.format(jDateCheckOut.getDate()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        long daysSpend = Check_Out_Date.getTime() - Check_In_Date.getTime();
        int Days = (int)(daysSpend /1000/60/60/24);
        
        if (comboRoomType.getSelectedItem().equals("Single")){
            
            txtYourBill.setText(Double.toString( Days * SingleRoom));
            txtTax.setText(Double.toString( Days * SingleRoom));
            txtTotal.setText(Double.toString( Days * SingleRoom));
                        
            double q = Double.parseDouble(txtTax.getText());
            q=(q * 0.25)/100;
            String tax = String.format(("$ %.2f"),q);
            txtTax.setText(tax);
            
            double t = Double.parseDouble(txtTotal.getText());
            String total = String.format(("$ %.2f"),t+q);
            txtTotal.setText(total);
            
        }
        else if (comboRoomType.getSelectedItem().equals("Double")){
            
            txtYourBill.setText(Double.toString( Days * DoubleRoom));
            txtTax.setText(Double.toString( Days * DoubleRoom));
            txtTotal.setText(Double.toString( Days * DoubleRoom));
                    
            double q = Double.parseDouble(txtTax.getText());
            q=(q * 0.25)/100;
            String tax = String.format(("$ %.2f"),q);
            txtTax.setText(tax);
            
            double t = Double.parseDouble(txtTotal.getText());
            String total = String.format(("$ %.2f"),(q+t));
            txtTotal.setText(total);
            
        }
        else if (comboRoomType.getSelectedItem().equals("Vila")){
            
            txtYourBill.setText(Double.toString( Days * Villa));
            txtTax.setText(Double.toString( Days * Villa));
            txtTotal.setText(Double.toString( Days * Villa));
            
            
            double q = Double.parseDouble(txtTax.getText());
            q=(q * 0.25)/100;
            String tax = String.format(("$ %.2f"),q);
            txtTax.setText(tax);
            
            double t = Double.parseDouble(txtTotal.getText());
            String total = String.format(("$ %.2f"),(q+t));
            txtTotal.setText(total);
            
        }
        else if (comboRoomType.getSelectedItem().equals("Apartment")){
            
            txtYourBill.setText(Double.toString( Days * Apartment));
            txtTax.setText(Double.toString( Days * Apartment));
            txtTotal.setText(Double.toString( Days * Apartment));
            
                     
            double q = Double.parseDouble(txtTax.getText());
            q=(q * 0.25)/100;
            String tax = String.format(("$ %.2f"),q);
            txtTax.setText(tax);
            
            double t = Double.parseDouble(txtTotal.getText());
            String total = String.format(("$ %.2f"),(q+t));
            txtTotal.setText(total);
            
        }
    }//GEN-LAST:event_TotalCostActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       
       txtCustomerRef.setText(null);
       txtFirstName.setText(null);
       txtLastName.setText(null);
       txtAddress.setText(null);
       txtCustomerMobile.setText(null);
       txtEmail.setText(null);
       jLocalNationality.setSelectedIndex(1);
       txtIdNo.setText(null);
       comboGender.setSelectedIndex(0);
       jDateCheckIn.setDate(null);
       jDateCheckOut.setDate(null);
       comboRoomType.setSelectedIndex(0);
       comboRoomNo.setSelectedIndex(0);
       comboRoomExtNo.setSelectedIndex(0);
       txtYourBill.setText(null);
       txtTax.setText(null);
       txtTotal.setText(null);
       
    }//GEN-LAST:event_ResetActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            txtCustomerRef.getText(),
            txtFirstName.getText(),
            txtLastName.getText(),
            txtAddress.getText(),
            txtCustomerMobile.getText(),
            txtEmail.getText(),
            jLocalNationality.getSelectedItem(),
            txtIdNo.getText(),
            comboGender.getSelectedItem(),
            jDateCheckIn.getDate(),
            jDateCheckOut.getDate(),
            comboRoomType.getSelectedItem(),
            comboRoomNo.getSelectedItem(),
            comboRoomExtNo.getSelectedItem(),
        });
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel CheckIn;
    private javax.swing.JLabel CheckOut;
    private javax.swing.JLabel CustomerMobile;
    private javax.swing.JLabel CustomerRef;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel IdNo;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Nationality;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel RoomExtNo;
    private javax.swing.JLabel RoomNo;
    private javax.swing.JLabel RoomType;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel Total;
    private javax.swing.JButton TotalCost;
    private javax.swing.JButton Update;
    private javax.swing.JLabel YourBill;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboRoomExtNo;
    private javax.swing.JComboBox<String> comboRoomNo;
    private javax.swing.JComboBox<String> comboRoomType;
    private com.toedter.calendar.JDateChooser jDateCheckIn;
    private com.toedter.calendar.JDateChooser jDateCheckOut;
    private com.toedter.components.JLocaleChooser jLocalNationality;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerMobile;
    private javax.swing.JTextField txtCustomerRef;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIdNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtYourBill;
    // End of variables declaration//GEN-END:variables
}
